---
- name: when demo
  hosts: all
  vars:
    supported_distros:
      - RedHat
      - CentOS
      - Fedora
  tasks:
    - name: install nginx pacakge in {{ supported_distros }}
      yum:
        name: nginx
        state: present
      when: ansible_distribution in supported_distros
...