---
- name: jenkins setup
  hosts: jenkins
  become: true
  tasks:
    - name: Install yum
      yum:
        name:
          - wget
          - java
        state: present

    - name: Download jenkins.repo
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins Key
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  # optional Task for checking     
    - name: "Import Jenkins key"
      command: "rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key"
      changed_when: false


    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true