---
- name: tomcat installation
  hosts: all
  become: true
  tasks:
    - name: update the system
      yum:
        name: "*"
        state: latest
    - name: install java
      yum:
        name: java
        state: present
    - name: select required java
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/java-1.8.0/bin/java
    - name: download tomcat
      get_url:
        url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.tar.gz
        dest: /opt
    - name: extracting download tomcat
      unarchive:
        src: /opt/apache-tomcat-8.5.68.tar.gz
        dest: /opt
        remote_src: yes
    - name: renaming tomcat name
      command: mv /opt/apache-tomcat-8.5.68  /opt/tomcat
    - name: start tomcat
      shell: nohup /opt/tomcat/bin/startup.sh &
